// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import "forge-std/Test.sol";
import "../src/EPoHBadge.sol";
import "../src/IssuerRegistry.sol";
import "../src/Verifier.sol";

/// @notice Integration test using the real HonkVerifier with a real ZK proof.
/// The proof bytes are loaded from a file via vm.readFile (must enable fs_permissions).
contract EPoHBadgeIntegrationTest is Test {
    EPoHBadge badge;
    HonkVerifier realVerifier;
    IssuerRegistry registry;
    address owner = address(this);
    address minter = address(0x1234);

    bytes32 constant ISSUER_PUBKEY_HASH = 0x16b085b3d759d330bcf290a3fdbf56595330d4acbd57e8ae9360f09e22206112;

    function setUp() public {
        realVerifier = new HonkVerifier();
        registry = new IssuerRegistry(owner);
        badge = new EPoHBadge(address(realVerifier), address(registry), owner);
        registry.addIssuer(ISSUER_PUBKEY_HASH);
        vm.warp(1700000000);
    }

    function test_mintWithRealProof() public {
        // Load proof from file (generated by prove.mjs)
        string memory proofHex = vm.readFile("test/fixtures/proof.hex");
        bytes memory proof = vm.parseBytes(proofHex);

        bytes32[] memory publicInputs = new bytes32[](4);
        publicInputs[0] = bytes32(uint256(0)); // claim_type = VACCINATED
        publicInputs[1] = bytes32(uint256(0x65554280)); // expires_at
        publicInputs[2] = 0x066941c7b276ab78294d1e1511090b6df9232b21561f5d203bd047a7d0732108;
        publicInputs[3] = 0x16b085b3d759d330bcf290a3fdbf56595330d4acbd57e8ae9360f09e22206112;

        vm.prank(minter);
        uint256 tokenId = badge.mintBadge(proof, publicInputs);
        assertEq(tokenId, 0);
        assertTrue(badge.isValid(0));

        EPoHBadge.Badge memory b = badge.getBadge(0);
        assertEq(b.claimType, 0);
        assertEq(b.expiresAt, 1700086400);
    }
}
